"""posts table

Revision ID: d15a958e8cbc
Revises: 641cf838f014
Create Date: 2021-04-23 13:02:56.598194

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd15a958e8cbc'
down_revision = '641cf838f014'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mission', sa.String(length=140), nullable=True),
    sa.Column('timestamp_start', sa.DateTime(), nullable=True),
    sa.Column('due_date', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_post_due_date'), 'post', ['due_date'], unique=False)
    op.create_index(op.f('ix_post_timestamp_start'), 'post', ['timestamp_start'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_post_timestamp_start'), table_name='post')
    op.drop_index(op.f('ix_post_due_date'), table_name='post')
    op.drop_table('post')
    # ### end Alembic commands ###
